# Tomcat Server
server:
  port: 8080

# Logging
logging:
  level:
    root: INFO
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG  # To see the logs, set the logging level for the advisor package to DEBUG:

# Spring Boot
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: edu
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html
  web:
    resources:
      static-locations: file:src/main/resources/static/
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-request-size: 20MB
      enabled: true
      max-file-size: 20MB
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 1.0
          max-tokens: 1000
#    openai:
#      api-key: ${GEMINI_KEY}
#      chat:
#        options:
#          model: gemini-3-flash-preview
#          temperature: 1.0
#          max-tokens: 1000
#        completions-path: /v1/chat/completions
#        base-url: https://generativelanguage.googleapis.com/v1beta/openai/

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: none
    tags-sorter: none
  group-configs:
    - group: Chapter_1_Chat_Completion_Controller
      paths-to-match: /ch1/**
    - group: Chapter_2_Prompt_Template_Controller
      paths-to-match: /ch2/**
    - group: Chapter_3_Advisor_Controller
      paths-to-match: /ch3/**
    - group: Chapter_4_Multimodality_API_Images_&_Vision_Controller
      paths-to-match: /ch4/**
    - group: Chapter_5_Multimodality_API_Audio_and_Speech_Controller
      paths-to-match: /ch5/**
