### package com.ai.controller.Ch1Controller

### 1. Chat (Zero-Shot Prompting)
### @("/completion")
POST http://localhost:8080/ch1/completion
Content-Type: application/x-www-form-urlencoded
Accept: text/plain

prompt=인천 부평의 맛집 알려줘.


### 2. Chat Stream
### @("/stream")
POST http://localhost:8080/ch1/stream
Content-Type: application/x-www-form-urlencoded
Accept: application/x-ndjson;charset=UTF-8

prompt=충남 예산 시장 가면 뭘 먹어야 할까??


### 3. Chat (Few-Shot Prompting)
### @("/few")
POST http://localhost:8080/ch1/few
Content-Type: application/x-www-form-urlencoded
Accept: application/x-ndjson;charset=UTF-8

prompt=충남 예산의 맛집 알려줘.


### 4. Chat (Chain-of-Thought Prompting)
### @("/chain")
POST http://localhost:8080/ch1/chain
Content-Type: application/x-www-form-urlencoded
Accept: application/x-ndjson;charset=UTF-8

prompt=1리터에 18km를 달리는 차가 서울에서 양양까지 시속 100km로 달렸을때 총 소요비용은??




