### package com.ai.controller.Ch3Controller

### 1. Advisor
### @("/completion")
POST http://localhost:8080/ch3/completion
Content-Type: application/x-www-form-urlencoded
Accept: text/plain;charset=UTF-8

prompt=테슬라 Y 차량에 대해 장점, 단점 알려줘.


### 2. Advisor stream
### @("/stream")
POST http://localhost:8080/ch3/stream
Content-Type: application/x-www-form-urlencoded
Accept: text/plain;charset=UTF-8

prompt=미국 ETF 중 나스닥에 해당하는 종목 1개 추천 해주고 이유를 설명 해줘

### 3. Recursive Advisors
### @("/bean-output")
POST http://localhost:8080/ch3/bean-output
Content-Type: application/x-www-form-urlencoded
Accept: application/json;charset=UTF-8

location=충남 예산&content=시장(장터)&language=Korean